import {
  Utensils,
  ShoppingCart,
  UtensilsCrossed,
  Coffee,
  Car,
  Fuel,
  Bus,
  CarTaxiFront,
  Home,
  Key,
  Wrench,
  Sofa,
  Receipt,
  Zap,
  Wifi,
  Smartphone,
  Repeat,
  ShoppingBag,
  Shirt,
  Laptop,
  Package,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  Film,
  Clapperboard,
  Gamepad2,
  Plane,
  Percent,
  CreditCard,
  TrendingUp,
  Landmark,
  Briefcase,
  PlusCircle,
  MoreHorizontal,
  Tag,
  PiggyBank,
  Wallet,
  Gift,
  Baby,
  GraduationCap,
  Dog,
  Cat,
  Music,
  Book,
  Umbrella,
  DollarSign,
  IndianRupee,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  "car-taxi-front": CarTaxiFront,
  home: Home,
  key: Key,
  wrench: Wrench,
  sofa: Sofa,
  receipt: Receipt,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  repeat: Repeat,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  laptop: Laptop,
  package: Package,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  film: Film,
  clapperboard: Clapperboard,
  "gamepad-2": Gamepad2,
  plane: Plane,
  percent: Percent,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  landmark: Landmark,
  briefcase: Briefcase,
  "plus-circle": PlusCircle,
  "more-horizontal": MoreHorizontal,
  tag: Tag,
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  gift: Gift,
  baby: Baby,
  "graduation-cap": GraduationCap,
  dog: Dog,
  cat: Cat,
  music: Music,
  book: Book,
  umbrella: Umbrella,
  "dollar-sign": DollarSign,
  "indian-rupee": IndianRupee,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export const DEFAULT_CATEGORY_ICON: LucideIcon = Tag;

export function getCategoryIcon(icon: string | null | undefined): LucideIcon {
  if (!icon) return DEFAULT_CATEGORY_ICON;
  return CATEGORY_ICONS[icon] ?? DEFAULT_CATEGORY_ICON;
}
